name: Hello, world!

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Your name."
        required: true
        default: "warning"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Create an HTML file with the name input value
      - name: Create HTML file
        run: echo "<html><body><div id='nameDisplay'>${{ github.event.inputs.name }}</div></body></html>" > index.html

      # Commit the HTML file back to the repository
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git commit -m "Add name to index.html"
          git push
